version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.06.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run: docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
      - run: docker pull shusugmt/hello-circle2:latest
      - run: docker build --cache-from shusugmt/hello-circle2:latest -t shusugmt/hello-circle2:latst .
      - run: docker push shusugmt/hello-circle2:latest
